In [35]:
from module import *

In [36]:
model = absenteeism_model('model', 'scaler')

/Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [37]:
model.load_and_clean_data('Absenteeism_new_data.csv')

In [38]:
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.873392,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.268305,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.196385,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.723502,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.716891,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.570524,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.134118,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.525007,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.454998,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.351108,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.096533,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.189479,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.499738,0
18,0,0.0,0,1,6,291,40,25,0,1,1,0.389531,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.500161,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.512352,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.351493,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.244943,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.491962,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.262240,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.966560,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.912399,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.746598,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.023090,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.295647,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.076450,0

In [39]:
df_output = model.predicted_outputs()

In [61]:
df_output.to_csv('out.csv')

In [40]:
pip install scikit-learn==0.22

Requirement already satisfied: scikit-learn==0.22 in /Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages (0.22)
Requirement already satisfied: numpy>=1.11.0 in /Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages (from scikit-learn==0.22) (1.19.2)
Requirement already satisfied: joblib>=0.11 in /Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages (from scikit-learn==0.22) (1.0.1)
Requirement already satisfied: scipy>=0.17.0 in /Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages (from scikit-learn==0.22) (1.5.2)
Note: you may need to restart the kernel to use updated packages.

In [41]:
!pip install pymysql

Requirement already satisfied: pymysql in /Users/sarathchandrikak/opt/anaconda3/envs/mysqlconnect/lib/python3.6/site-packages (1.0.2)

In [42]:
import pymysql

In [43]:
conn = pymysql.connect(database = 'predicted_outputs', user ='root', password= 'pass123')

In [44]:
cursor = conn.cursor()

In [56]:
cursor.execute("SELECT * FROM predicted_outputs;")

80

In [46]:
insert_query = "INSERT INTO predicted_outputs VALUES"

In [47]:
insert_query

'INSERT INTO predicted_outputs VALUES'

In [48]:
df_output.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet', 'Probability', 'Prediction'], dtype=object)

In [49]:
df_output.shape

(40, 13)

In [50]:
for i in range(df_output.shape[0]):
    insert_query += '('
    for j in range(df_output.shape[1]):
        insert_query += str(df_output[df_output.columns.values[j]][i]) + ', '
        
    insert_query = insert_query[:-2] + ' ), '

In [51]:
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1227992624349432, 0 ), (1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8733923470447209, 1 ), (0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.26830495460343223, 0 ), (0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.1963853143922252, 0 ), (1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7235017225544896, 1 ), (1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7168905020985188, 1 ), (1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5705238370679658, 1 ), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1227992624349432, 0 ), (0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13411805408968352, 0 ), (1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5250065611752316, 1 ), (0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.45499802072862455, 0 ), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1 ), (0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.35110766120784753, 0 ), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1227992624349432, 0 ), (0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.09653346354354148, 0 ), (0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.1894785903905003, 0 ), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1 ), (1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.49973827165859186, 0 ), (0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.38953149469289, 0 ), (1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.5001612226284466, 1 ), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0 ), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0 ), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1 ), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1 ), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0 ), (0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.5123518738925141, 1 ), (0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.35149320375017246, 0 ), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1 ), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0 ), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1 ), (0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.24494273576137351, 0 ), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0 ), (0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.4919621401501115, 0 ), (0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.26224032774538253, 0 ), (1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.966560156232829, 1 ), (1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9123989237228621, 1 ), (1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7465975923060953, 1 ), (0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.023089501687401086, 0 ), (0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.29564748904572213, 0 ), (0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.07644956838010682, 0 ), '

In [52]:
insert_query = insert_query[:-2] + ';'

In [53]:
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1227992624349432, 0 ), (1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8733923470447209, 1 ), (0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.26830495460343223, 0 ), (0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.1963853143922252, 0 ), (1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7235017225544896, 1 ), (1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7168905020985188, 1 ), (1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5705238370679658, 1 ), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1227992624349432, 0 ), (0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13411805408968352, 0 ), (1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5250065611752316, 1 ), (0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.45499802072862455, 0 ), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1 ), (0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.35110766120784753, 0 ), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1227992624349432, 0 ), (0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.09653346354354148, 0 ), (0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.1894785903905003, 0 ), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1 ), (1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.49973827165859186, 0 ), (0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.38953149469289, 0 ), (1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.5001612226284466, 1 ), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0 ), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0 ), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1 ), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1 ), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0 ), (0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.5123518738925141, 1 ), (0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.35149320375017246, 0 ), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1 ), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0 ), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1 ), (0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.24494273576137351, 0 ), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0 ), (0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.4919621401501115, 0 ), (0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.26224032774538253, 0 ), (1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.966560156232829, 1 ), (1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9123989237228621, 1 ), (1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7465975923060953, 1 ), (0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.023089501687401086, 0 ), (0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.29564748904572213, 0 ), (0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.07644956838010682, 0 );'

In [55]:
cursor.execute(insert_query)

40

In [57]:
conn.commit()

In [58]:
conn.close()